Generate overlay with final and prev parameters
Otherwise `nix flake check` complains with:

    error: overlay does not take an argument named 'final'

This also changes which callPackage is called. Previously, we used
"super" (now prev), but we changed it to "final", because this seems
to be more correct (i.e. used in nixpkgs).