flake.lock: Update to patched nix-ros-overlay that works with nixos-unstable
Python packages, such as rosdep, need to be updated to not fail with:

    error: python3.13-rosdep-0.25.1 does not configure a `format`. To
    build with setuptools as before, set `pyproject = true` and
    `build-system = [ setuptools ]`.`

See https://github.com/lopsided98/nix-ros-overlay/pull/644.

Flake lock file updates:

• Updated input 'nix-ros-overlay':
    'github:lopsided98/nix-ros-overlay/31e1e361f41a0e4116d4c34eb608931dfd101492?narHash=sha256-IYfuTysAvph03Iyc/XwuM04yd0qJhm/OtziZglwYys0%3D' (2024-09-27)
  → 'github:lopsided98/nix-ros-overlay/64dac510bb4ab62670c9c24177fde776ad4dfd71?narHash=sha256-2v2w2GDwerBmrJqa6oyDMI6E1TmeVbWXJbpf1kq37GA%3D' (2025-07-05)
• Updated input 'nix-ros-overlay/flake-utils':
    'github:numtide/flake-utils/1ef2e671c3b0c19053962c07dbda38332dcebf26?narHash=sha256-uNRRNRKmJyCRC/8y1RqBkqWBLM034y4qN7EprSdmgyA%3D' (2024-01-15)
  → 'github:numtide/flake-utils/11707dc2f618dd54ca8739b309ec4fc024de578b?narHash=sha256-l0KFg5HjrsfsO/JpG%2Br7fRrqm12kzFHyUHqHCVpMMbI%3D' (2024-11-13)